### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by peterglock** [j5int/virtualtime#9]
I'm attempting to use virtual time to overcome the pre-1900 problems on python 2.7.13 / django 1.11 application. In the application, dates are picked from a django form using `forms.DateField`. I can't find any documentation about how to ensure that virtualtime is being used. 

I have tried importing virtualtime to the app's forms.py and views.py using `import virtualtime` but get the error 
`File "apps/whathappenedthen/views.py", line 75, in get_context_data
    "day": this_day.strftime("%d %B %Y")
ValueError: year=1897 is before 1900; the datetime strftime() methods require year >= 1900`

How do I ensure that strftime() is patched?

**Comment by dave42** [comment]
Make sure virtualtime is imported before anything else - if django caches the datetime object it imports, you need to make sure the datetime that django imports is the patched one.

**Comment by peterglock** [comment]
OK. Here are the first two lines of my views.py:
```
import virtualtime
import datetime
```

But when I call strftime with 

```
        this_day = datetime.date(**kwargs)
...
            "day": this_day.strftime("%d %B %Y")


```
I get 

```
  File "apps/whathappenedthen/views.py", line 76, in get_context_data
    "day": this_day.strftime("%d %B %Y")
ValueError: year=1897 is before 1900; the datetime strftime() methods require year >= 1900
```

How do I make the patch 'stick'?

**Comment by peterglock** [comment]
More research...

Changing `datetime.date` to `datetime.datetime` fixes the problem. I'll close the issue. Might be useful for others that are having similar problems.

The learnings are:

1. Put `import virtualtime` at the beginning rather than after other imports
2. Look out for `datetime.date` as it is **not** patched
